import { PatientService } from '../modules/patients/service';
import { ClinicalService } from '../modules/clinical/service';
import { PrismaPatientRepository } from '../modules/patients/prisma-repository';
import { InventoryService } from '../modules/inventory/service';
import { SalesService } from '../modules/sales/service';
import { LaboratoryService } from '../modules/laboratory/service';
import { CashService } from '../modules/cash/service';
import { BillingService } from '../modules/billing/service';
import { prismaClinicalService } from '../modules/clinical/prisma-service';
import { prismaInventoryService } from '../modules/inventory/prisma-service';
import { prismaSalesService } from '../modules/sales/prisma-service';
import { prismaLaboratoryService } from '../modules/laboratory/prisma-service';
import { prismaCashService } from '../modules/cash/prisma-service';

export const patientService = new PatientService();
export const clinicalService = new ClinicalService();
export { prismaClinicalService };
export { prismaInventoryService, prismaSalesService, prismaLaboratoryService, prismaCashService };
export const prismaPatientRepository = new PrismaPatientRepository();
export const inventoryService = new InventoryService();
export const salesService = new SalesService();
export const laboratoryService = new LaboratoryService();
export const cashService = new CashService();
export const billingService = new BillingService();
